[tool.isort]
line_length = 120
profile = "black" 

[tool.black]
line-length=120

[tool.pydocstyle]
convention = "numpy"

[tool.pylint.format]
max-line-length = 120
good-names = ["df", "DataFrame"]
disable = "C0411"
fail-under = 9.5
fail-on = ["F", "E"]'
